### ISSUE TITLE
接收数据显示异常

### ISSUE THREAD

**Issue by YZX1227057471** [xmaihh/Android-Serialport#10]
接收串口数据的时候数据被分成了很多段，请问下这怎么解决呐

**Comment by xmaihh** [comment]
通过约定通信协议来实现数据格式化，比如通过数据的帧头帧尾进行判断是否为完整数据帧、通过帧头和数据帧长来判断完整帧、加入定时器将延时读取的数据存入缓冲区然后timeout后再一次性读取数据
