### ISSUE TITLE
频繁的open ，close 会导致内存泄漏

### ISSUE THREAD

**Issue by ZHOUCHAOzzz** [xmaihh/Android-Serialport#11]
我在oncreate里 open，在onDestroy close 这样我来回进入这个页面几次就会导致内存泄漏，这个怎么解决

**Comment by xmaihh** [comment]
在一系列操作中，最好就是先打开端口，等待所有操作结束后在关端口，中间不要开关。建议在Application这种生命周期长的对象操作串口的打开和关闭。
