### ISSUE TITLE
目前读取回调onDataReceived中，不管发送的数据包多大，总是拿到63字节的缓冲区。无法确定收到数据的大小。

### ISSUE THREAD

**Issue by wildfire810** [xmaihh/Android-Serialport#12]
如题
目前在SerialHelper的读取回调onDataReceived中，不管发送的数据包多大，总是拿到63字节的缓冲区。无法确定收到数据的大小。

**Comment by wildfire810** [comment]
byte[] buffer = getStickPackageHelper().execute(SerialHelper.this.mInputStream);
                    if (buffer != null && buffer.length > 0) {
                        ComBean ComRecData = new ComBean(SerialHelper.this.sPort, buffer, buffer.length);
                        SerialHelper.this.onDataReceived(ComRecData);
                    }
//                    int available = SerialHelper.this.mInputStream.available();
//
//                    if (available > 0) {
//                        byte[] buffer = new byte['?'];
//                        int size = SerialHelper.this.mInputStream.read(buffer);
//                        if (size > 0) {
//                            ComBean ComRecData = new ComBean(SerialHelper.this.sPort, buffer, size);
//                            SerialHelper.this.onDataReceived(ComRecData);
//                        }
//                    } else {
//                        SystemClock.sleep(50);
//                    }

这个地方，没有处理读取到的长度

**Comment by xmaihh** [comment]
默认实现的是 [BaseStickPackageHelper](https://github.com/xmaihh/Android-Serialport/blob/master/serialport/src/main/java/tp/xmaihh/serialport/stick/BaseStickPackageHelper.java)，
```java
 @Override
    public byte[] execute(InputStream is) {
        try {
            int available = is.available();
            if (available > 0) {
                byte[] buffer = new byte['?'];
                int size = is.read(buffer);
                if (size > 0) {
                    return buffer;
                }
            } else {
                SystemClock.sleep(50);
            }

        } catch (IOException e) {
            e.printStackTrace();
        }
        return null;
    }
```
可以看到` byte[] buffer = new byte['?'];`，定义了一个长度为63的字节数组（？的ascii值为63），所以总是返回63字节的数据。

**Comment by wildfire810** [comment]
谢谢。能看懂了。
