### ISSUE TITLE
要发送多次才有响应数据为什么

### ISSUE THREAD

**Issue by guodonghuang** [xmaihh/Android-Serialport#13]
发送一次指令要发3次-4次才有数据返回，而且会有重复数据，最后还有一大串0000000000，为什么呀大佬？
比如：发送  FAFB0C10000055AB,
第一次
第二次
第三次
响应数据：  FC0C1000016132ADFAFC0C100001DA89ADFAFC0C100001EFBCADFAFC0C10000100000000000000000000000000000000000000000000000000000000000000

按理来说应该是：  FAFC0C100001DA89AD

是不是第一次发送阻塞了，还是怎么回事，求大佬指教呀

**Comment by xmaihh** [comment]
请参考[iissues12](https://github.com/xmaihh/Android-Serialport/issues/12)
