### ISSUE TITLE
发送后收不到回应，请问这是什么情况

### ISSUE THREAD

**Issue by Dwhy** [xmaihh/Android-Serialport#14]
导入包然后复制demo里面的代码，发送后收不到回应，没有任何回应，请问这是什么情况

**Comment by Dwhy** [comment]
` serialHelper.setStickPackageHelper(new AbsStickPackageHelper() {
            @Override
            public byte[] execute(InputStream inputStream) {
                byte[] buffer = new byte[1024];
                try {
                    int size= inputStream.read(buffer);
                    byte[] data=new byte[size];
                    System.arraycopy(buffer,0,data,0,size);
                    Log.i(TAG, "CacheThread: 接收：" + MessageUtils.getInstance().bytesToHexString(data));
                } catch (IOException e) {
                    Log.e(TAG, "run: 数据读取异常：" +e.toString());
                }
                return new byte[0];
            }
        });`
        实现AbsStickPackageHelper接口发送多次能收到一次回复

**Comment by Dwhy** [comment]
`
serialHelper.setStickPackageHelper(new AbsStickPackageHelper() {
            @Override
            public byte[] execute(InputStream inputStream) {
                byte[] buffer = new byte[1024];
                try {
                    int size= inputStream.read(buffer);
                    byte[] data=new byte[size];
                    System.arraycopy(buffer,0,data,0,size);
                    Log.i(TAG, "CacheThread: 接收：" + MessageUtils.getInstance().bytesToHexString(data));
                } catch (IOException e) {
                    Log.e(TAG, "run: 数据读取异常：" +e.toString());
                }
                return new byte[0];
            }
        

> });

`
实现AbsStickPackageHelper接口发送多次能收到一次回复

**Comment by SimonTse** [comment]
> 导入包然后复制demo里面的代码，发送后收不到回应，没有任何回应，请问这是什么情况

请问下您解决了这个问题吗？我这里也遇到了能正常打开串口并控制硬件开关，但是硬件返回的数据我这里收不到任何消息。如果解决了，麻烦告知一下，多谢！

**Comment by xmaihh** [comment]
`@Override
    public byte[] execute(InputStream is) {
        try {
            int available = is.available();
            if (available > 0) {
                byte[] buffer = new byte[1024];
                int size = is.read(buffer);
                if (size > 0) {
                    return buffer;
                }
            } else {
                SystemClock.sleep(50);
            }

        } catch (IOException e) {
            e.printStackTrace();
        }
        return null;
    }`

**Comment by xmaihh** [comment]
> ```
> @Override
>     public byte[] execute(InputStream is) {
>         try {
>             int available = is.available();
>             if (available > 0) {
>                 byte[] buffer = new byte[1024];
>                 int size = is.read(buffer);
>                 if (size > 0) {
>                     return buffer;
>                 }
>             } else {
>                 SystemClock.sleep(50);
>             }
> 
>         } catch (IOException e) {
>             e.printStackTrace();
>         }
>         return null;
>     }
> ```
