### ISSUE TITLE
Baudrate issue

### ISSUE THREAD

**Issue by manoj-awak** [xmaihh/Android-Serialport#18]
I am sending 55 from dev/ttyCOM3 with 203400 as baudrate and at the other end i am recieving B5 with the same baudrate at dev/ttyS1.
But If I do the same above with 115200 baudrate both ends data is same not changing.

I want to recieve similiar data with higher baudrate. 

Where is the problem?

**Comment by xmaihh** [comment]
Baud Rate (Baud Rate) in bps -- Byte Per Second.

Baud rate indicates the number of code symbols transmitted per second. It is a measure of data transmission rate, expressed in terms of the number of times the carrier modulation state changes per unit of time. Baud rate refers to the modulation rate of the data signal to the carrier, expressed in terms of the number of times the carrier modulation state changes per unit of time, and its unit is baud (Baud).

According to the physical characteristics of electricity, transmission medium, etc. combined with the requirements of the serial device, to ensure effective communication, it is determined that the maximum transmission rate of RS232 can only be 115200.
