### ISSUE TITLE
请问两个问题？

### ISSUE THREAD

**Issue by candebbs** [xmaihh/Android-Serialport#19]
1.可以同时支持多个串口读取数据吗？
2.一次读取数据有限长度吗？比如一次写2M以上的数据？

**Comment by xmaihh** [comment]
1.不支持
2.见[issues#12](https://github.com/xmaihh/Android-Serialport/issues/12)

**Comment by candebbs** [comment]
1.可以考虑支持，一个板子会接多个串口的。

**Comment by xmaihh** [comment]
暂无精力支持多个串口读取数据，多个串口读数据可考虑继承[SerialHelper](https://github.com/xmaihh/Android-Serialport/blob/master/serialport/src/main/java/tp/xmaihh/serialport/SerialHelper.java#L17)来实现

**Comment by candebbs** [comment]
好的，换一个思路来可以做到了，就可以不支持。
