### ISSUE TITLE
软件长时间运行，读取不到信息

### ISSUE THREAD

**Issue by xSmile-art** [xmaihh/Android-Serialport#21]
软件长时间运行，一连运行一个星期以上的时候，就读取不到信息，是发生串口宕机吗？

**Comment by xmaihh** [comment]
如您提供的这些信息，无法回答，这需要您自己排查是软件的问题还是硬件问题

**Comment by Mkean** [comment]
那请教下，串口一个长时间保持 open 状态，串口会不会发生死机的情况？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年02月27日 11:40 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [xmaihh/Android-Serialport] 软件长时间运行，读取不到信息 (Issue #21) |

如您提供的这些信息，无法回答，这需要您自己排查是软件的问题还是硬件问题

**Comment by xmaihh** [comment]
造成串口死机的原因：
1、代码问题
2、硬件问题

**Comment by Amyitis** [comment]
确实存在这种长时间保持串口连接状态会出故障的BUG。
1.在线程中开启串口open
2.在同线程中保持一个死循环，每1500毫秒间隔 轮询一个 指令池队列，有指令就发送串口指令，没有就无动作继续轮询；
3.刚启动这个线程的时候，能稳定按队列的指令逐条执行，但是一但串口open时间过长，就只能执行一次指令，并且得不到正确的串口反馈信息（回调）。

**Comment by xmaihh** [comment]
为避免消耗电池电量，处于空闲状态的 Android 设备会快速进入休眠模式。

需要长时间保持串口连接状态可以考虑：1.使屏幕保持开启状态 2.使 CPU 保持运行状态 。
