### ISSUE TITLE
FileDescriptor is not finalized or released.

### ISSUE THREAD

**Issue by MarFreit1996** [xmaihh/Android-Serialport#25]
during some tests I noticed that if I call the 'serialHelper.open()' method twice in a row even calling 'serialHelper.close()' in 'onDestroy()', it creates another FileDescriptor , and with that I can no longer read the serial data.

```
 public void close() {
        if (this.mReadThread != null) {
            this.mReadThread.interrupt();
        }

        if (this.mSerialPort != null) {
            this.mSerialPort.close();
            this.mSerialPort = null;
        }

        this._isOpen = false;
    }
```

![image](https://github.com/xmaihh/Android-Serialport/assets/136738529/11a1a794-f17e-43b6-8b92-2123ef889154)

after running the opening I get in logcat:
![image](https://github.com/xmaihh/Android-Serialport/assets/136738529/fe0f7c46-9091-4f4d-ba5a-d58e19649ab7)

Now, if I destroy the activity, and run it again, look what happens

![image](https://github.com/xmaihh/Android-Serialport/assets/136738529/d50a55ff-bf3b-4ed5-8985-a17b60f88b8d)

**Comment by xmaihh** [comment]
Please avoid calling `serialHelper.open()` multiple times.

There are two ways to avoid calling `serialHelper.open()` multiple times:

1. Use a variable to record whether the serial port has been opened. Set it to true when calling `serialHelper.open()` for the first time, and then check if the variable is true before calling it again. If it is true, do not execute `serialHelper.open()` again.

2. Add a judgment in the `serialHelper.open()` method to directly return if the serial port has already been opened. This way, even if called multiple times, it will not have any impact.
