### ISSUE TITLE
串口关闭

### ISSUE THREAD

**Issue by whl0718** [xmaihh/Android-Serialport#29]
<code>SerialHelper</code>类open方法打开了一个SendThread

close方法关闭的时候没有关闭SendThread，这不会出问题嘛

**Comment by xmaihh** [comment]
如果你使用SerialHelper类的`open()`方法打开一个串口连接时，它将会创建并启动一个`SendThread`线程来发送数据。

当你调用`close()`方法关闭连接时，它只会关闭`InputStream`和`OutputStream`对象，并不会直接关闭`SendThread`线程。但这不会出现问题，因为当流关闭时，阻塞在读取数据或等待写入数据的线程都将接收到IOException异常，并因此退出线程。

在`SendThread`线程中，它会不断地从发送队列（`Queue`）中获取要发送的数据，并将其写入输出流中发送。如果你需要停止`SendThread`线程，你可以通过设置一个标志位的方式来结束循环，例如在发送队列中添加一个特殊的结束标志或者手动修改标志位，以通知线程停止执行任务并退出循环。

当线程检测到结束标志或标志位被设置时，它会清空发送队列 并关闭输出流和输入流，随后释放和销毁相关资源，完成线程的结束。

总之，SerialHelper类的`SendThread`是一个安全可靠的实现方式，理论上不会出现内存泄漏或资源占用过多的情况。但是在使用时需要注意正确的使用方式和异常处理，以避免潜在的问题。
