### ISSUE TITLE
接收到的数据好像是定长126位？后面都是补0

### ISSUE THREAD

**Issue by noobzhp** [xmaihh/Android-Serialport#3]

**Comment by xmaihh** [comment]
默认依赖库里面并没有对接收数据长度限制,根据设置的波特率取的数据,可以方便详细说明一下 你使用的波特率和设置的`serialHelper.setStickPackageHelper(AbsStickPackageHelper mStickPackageHelper);`

**Comment by jotyy** [comment]
我也遇到这个问题，怎么解决呢？

**Comment by xmaihh** [comment]
> 我也遇到这个问题，怎么解决呢？

配合PC端串口助手查找问题
