### ISSUE TITLE
你好我想问一下，咱们这个支持   ModBus通讯协议，RTU模式  吗？

### ISSUE THREAD

**Issue by hhh5022456** [xmaihh/Android-Serialport#31]

**Comment by xmaihh** [comment]
Modbus通讯协议的RTU模式本质上是通过串口进行通信。我这个是一个串口库，配置串口参数，例如波特率、数据位、奇偶校验位和停止位等。您需要自行实现Modbus RTU协议的消息封装和解析逻辑。
