### ISSUE TITLE
运行demo，从demo发送数据正常，但是接收不到从pc发送的数据

### ISSUE THREAD

**Issue by pbaiyy** [xmaihh/Android-Serialport#32]
RT

**Comment by xmaihh** [comment]
请使用 V2.1.1版本
```shell
implementation 'io.github.xmaihh:serialport:2.1.1'
```

**Comment by pbaiyy** [comment]
pc发送一条长一点的消息，Android就会分多次收到，这种需要怎么处理呢？

**Comment by pbaiyy** [comment]
> 请使用 V2.1.1版本
> 
> ```shell
> implementation 'io.github.xmaihh:serialport:2.1.1'
> ```
> 
> 新版本试验性支持自定义波特率的功能，受限于手头测试环境未能充分测试，请先使用旧版本，您可以在以下位置下载到旧版本demo
> 
> https://github.com/xmaihh/Android-Serialport/releases/tag/v2.1.1


pc发送一条长一点的消息，Android就会分多次收到，这种需要怎么处理呢？

**Comment by xmaihh** [comment]
处理串口通信时，您需要根据具体的通信协议和数据格式来确定适合您应用的处理方式

1. 缓冲区处理：创建一个缓冲区来存储接收到的数据。当接收到部分数据时，将其添加到缓冲区中，然后检查是否已经接收到完整的消息。

2. 消息分割处理：如果您知道消息的结束标志（例如换行符或特定字符），您可以使用它们来判断消息是否已经接收完整。当接收到数据时，将其附加到缓冲区，并检查缓冲区中是否存在结束标志。如果存在结束标志，表示接收到完整的消息，您可以处理该消息并清空缓冲区。如果不存在结束标志，继续等待下一次数据的到来。

3. 数据长度处理：如果消息的长度是固定的，您可以根据消息的长度来判断是否已经接收到完整的消息。当接收到数据时，将其附加到缓冲区，并检查缓冲区中的数据长度是否达到预期的消息长度。如果达到了，表示接收到完整的消息，您可以处理该消息并清空缓冲区。如果长度不足，继续等待下一次数据的到来。

**Comment by xmaihh** [comment]
可参考这一节[7.粘包处理](https://github.com/xmaihh/Android-Serialport#7%E7%B2%98%E5%8C%85%E5%A4%84%E7%90%86)

**Comment by pbaiyy** [comment]
> 可参考这一节[7.粘包处理](https://github.com/xmaihh/Android-Serialport#7%E7%B2%98%E5%8C%85%E5%A4%84%E7%90%86)

项目中的termios.h是不是冗余的文件，我发现SerialPort.c中引用的termios还是源码中的termios.h，项目中的这个文件可否删除？

**Comment by xmaihh** [comment]
可删除

**Comment by xmaihh** [comment]
> > 可参考这一节[7.粘包处理](https://github.com/xmaihh/Android-Serialport#7%E7%B2%98%E5%8C%85%E5%A4%84%E7%90%86)
> 
> 项目中的termios.h是不是冗余的文件，我发现SerialPort.c中引用的termios还是源码中的termios.h，项目中的这个文件可否删除？

可

**Comment by pbaiyy** [comment]
> > > 可参考这一节[7.粘包处理](https://github.com/xmaihh/Android-Serialport#7%E7%B2%98%E5%8C%85%E5%A4%84%E7%90%86)
> > 
> > 
> > 项目中的termios.h是不是冗余的文件，我发现SerialPort.c中引用的termios还是源码中的termios.h，项目中的这个文件可否删除？
> 
> 可

我的项目中，多个页面，都需要用到串口，所以我希望整个项目的串口open，只调用一次，但是，现在我发现，onDataReceived这个接收数据的方法，好像就算多个地方写，也只有一个地方能接收到。这种怎么处理呢？

**Comment by xmaihh** [comment]
如果你希望在多个页面中同时接收串口数据，可以考虑将串口通信的逻辑集中在一个单独的类中，而不是在每个页面中创建独立的串口实例。这样可以确保只调用一次 open 方法，但允许多个地方注册并接收串口数据。

**Comment by pbaiyy** [comment]
> 如果你希望在多个页面中同时接收串口数据，可以考虑将串口通信的逻辑集中在一个单独的类中，而不是在每个页面中创建独立的串口实例。这样可以确保只调用一次 open 方法，但允许多个地方注册并接收串口数据。

如果我是在每个页面的onresume和onstop开关串口，这么频繁的开关，会导致其他问题吗？

**Comment by xmaihh** [comment]
频繁地在每个页面的 onResume 和 onStop 方法中开关串口可能会引发一些问题，
1. 性能开销增加：每次切换页面都调用开关串口的方法，会导致不必要的资源消耗。这可能会对应用程序的性能产生负面影响，特别是在较低端设备上或者串口通信数据量较大的情况下。

2. 串口状态不一致：如果在一个页面中关闭了串口，而在另一个页面中又重新打开了串口，可能会导致串口状态不一致。这可能导致无法正常接收或发送数据，或者引发其他与串口状态相关的问题。
