### ISSUE TITLE
能打开串口，但是接收不到消息！

### ISSUE THREAD

**Issue by taomf** [xmaihh/Android-Serialport#34]
波特率，数据位，停止位，这些设置都没有问题，发送数据也没问题，就是收不到数据。

**Comment by xmaihh** [comment]
哪个版本

**Comment by taomf** [comment]
io.github.xmaihh:serialport:2.1.1

**Comment by xmaihh** [comment]
2.1.1是正常的，不会出现这种情况，请再检查
1.电缆连接问题：检查串口电缆是否正确连接，并确保连接牢固。一个松动或损坏的连接可能导致数据无法正常传输。

2.接收端程序问题：确保接收端程序正确运行并正在监听串口。如果接收端没有正确打开串口或没有设置正确的接收逻辑，就无法接收到数据。

3.数据冲突或干扰：有时，当同时进行多路串口通信或存在其他干扰源时，数据可能会发生冲突或干扰，导致接收端无法正确解析数据。检查是否存在其他设备或干扰源，尝试在清静的环境中进行测试。

**Comment by taomf** [comment]
知道刚刚的那个问题，有另外一个工具也在接收那个消息，有干扰，导致这个边接收不到。
但又碰到了一个新问题，只有在开启串口时能收到一条消息，后续的消息都收不到了。
