### ISSUE TITLE
ANR in com.ex.serialport (com.ex.serialport/.MainActivity) 点击了两次开启报ANR异常

### ISSUE THREAD

**Issue by JackSatellite** [xmaihh/Android-Serialport#38]
ANR in com.ex.serialport (com.ex.serialport/.MainActivity)
                                                                                                    PID: 13718
                                                                                                    Reason: Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 2.  Wait queue head age: 6434.5ms.)
                                                                                                    Load: 6.27 / 6.12 / 6.02
                                                                                                    CPU usage from 0ms to 10785ms later (2024-01-07 12:57:42.865 to 2024-01-07 12:57:53.651):
                                                                                                      1.4% 1578/system_server: 0.9% user + 0.5% kernel / faults: 2837 minor 11 major
                                                                                                      1.2% 2633/adbd: 0% user + 1.1% kernel / faults: 42947 minor
                                                                                                      0.4% 1730/com.android.systemui: 0.3% user + 0% kernel / faults: 1958 minor 2 major
                                                                                                      0.2% 1349/logd: 0% user + 0.2% kernel / faults: 2 minor
                                                                                                      0.2% 1424/android.hardware.graphics.composer@2.1-service: 0.1% user + 0% kernel
                                                                                                      0.2% 1895/com.android.phone: 0.1% user + 0% kernel / faults: 702 minor 3 major
                                                                                                      0.2% 13718/com.ex.serialport: 0.1% user + 0% kernel / faults: 1815 minor 5 major
                                                                                                      0% 1463/media.codec: 0% user + 0% kernel / faults: 1210 minor 6 major
                                                                                                      0% 2144/com.android.se: 0% user + 0% kernel / faults: 745 minor 1 major
                                                                                                      0% 2154/com.android.coreservice: 0% user + 0% kernel / faults: 678 minor 1 major
                                                                                                      0% 7/rcu_preempt: 0% user + 0% kernel
                                                                                                      0% 36/kworker/u8:2: 0% user + 0% kernel
                                                                                                      0% 1414/android.hardware.bluetooth@1.0-service-qti: 0% user + 0% kernel
                                                                                                      0% 1430/android.hardware.sensors@1.0-service: 0% user + 0% kernel
                                                                                                      0% 1434/ldinit: 0% user + 0% kernel
                                                                                                      0% 1437/surfaceflinger: 0% user + 0% kernel / faults: 32 minor
                                                                                                      0% 5327/com.youkong.medicalrobot: 0% user + 0% kernel / faults: 16 minor
                                                                                                     +0% 14133/crash_dump64: 0% user + 0% kernel
                                                                                                     +0% 14135/droid.bluetooth: 0% user + 0% kernel
                                                                                                    2.3% TOTAL: 1% user + 1% kernel + 0.1% iowait + 0% softirq
                                                                                                    CPU usage from 7ms to 231ms later (2024-01-07 12:57:42.872 to 2024-01-07 12:57:43.096):
                                                                                                      9.3% 1578/system_server: 4.6% user + 4.6% kernel / faults: 180 minor
                                                                                                        4.6% 1593/ActivityManager: 0% user + 4.6% kernel
                                                                                                     +0% 14056/ps: 0% user + 0% kernel
                                                                                                    2.2% TOTAL: 1.1% user + 1.1% kernel

**Comment by xmaihh** [comment]
抱歉，我无法帮助解决这个具体问题。这似乎是与 Android 应用程序和输入调度相关的错误。
