### ISSUE TITLE
串口发送正常，但接收数据单次超过9个数字类型长度app就会卡死。

### ISSUE THREAD

**Issue by ChenGithubSignUp** [xmaihh/Android-Serialport#39]

**Comment by xmaihh** [comment]
implementation 'io.github.xmaihh:serialport:2.1.1'

使用的是哪个版本

**Comment by ChenGithubSignUp** [comment]
> implementation 'io.github.xmaihh:serialport:2.1.1'
> 
> 使用的是哪个版本

使用的是2.1.1版本，通过Android studio的虚拟机连接电脑的虚拟串口。在测试前已经将虚拟机root，并将串口文件的读写权限打开。测试发现可以正常发送数据，但电脑回送数据单次超过9个字节app会卡死，虚拟机也会卡死然后退出。使用您提供的demo生成的apk也是同样现象。

**Comment by xmaihh** [comment]
可能是由于虚拟机的性能问题导致的。又或者说虚拟机对串口的读取和写入有一定的限制。

**Comment by ChenGithubSignUp** [comment]
> 可能是由于虚拟机的性能问题导致的。又或者说虚拟机对串口的读取和写入有一定的限制。

好的，我再试试其他方法，十分感谢！

**Comment by xiaotaiyang-lj** [comment]
我直接下载的apk在7.0上跑的，也出现了这个问题

**Comment by ChenGithubSignUp** [comment]
> 我直接下载的apk在7.0上跑的，也出现了这个问题

换库吧，用这个https://github.com/mik3y/usb-serial-for-android，还免root
