### ISSUE TITLE
在Android 10.0版本上报错：Cannot run program "/system/bin/su": error=2, No such file or directory

### ISSUE THREAD

**Issue by Cqucyf1** [xmaihh/Android-Serialport#41]
我百度了一下，需要把/system/bin/su修改为/system/bin/sh

https://blog.csdn.net/weixin_43266090/article/details/108245698

希望能修正一下

**Comment by xmaihh** [comment]
此library不提供ROOT权限,请自行打开串口666权限

**Comment by gaidukov76** [comment]
Maybe you need change the path /system/bin/su to /system/xbin/su

**Comment by xmaihh** [comment]
> Maybe you need change the path /system/bin/su to /system/xbin/su

[What special privileges "/system/xbin/su" does have w.r.t. root access?](https://android.stackexchange.com/questions/207623/what-special-privileges-system-xbin-su-does-have-w-r-t-root-access)
