### ISSUE TITLE
Class 'FileDescriptor' has no field named 'descriptor'. 

### ISSUE THREAD

**Issue by master5277** [xmaihh/Android-Serialport#42]
jclass cFileDescriptor = env->FindClass("java/io/FileDescriptor");
jmethodID iFileDescriptor = env->GetMethodID(cFileDescriptor,"","()V");
jfieldID descriptorID = env->GetFieldID( cFileDescriptor, "descriptor", "I");
mFileDescription = env->NewObject(cFileDescriptor,iFileDescriptor);
env->SetIntField(mFileDescription,descriptorID,(jint)fd);

Android Studio 4.1.1 says "Class 'FileDescriptor' has no field named 'descriptor'. "

**Comment by xmaihh** [comment]
In Android Studio 4.1.1, the java.io.FileDescriptor class does not have a field named "descriptor". Instead, it has a field named "fd". To access the file descriptor value, you can use the following code:

```
jclass cFileDescriptor = env->FindClass("java/io/FileDescriptor");
jmethodID iFileDescriptor = env->GetMethodID(cFileDescriptor,"","()V");
jfieldID fdID = env->GetFieldID(cFileDescriptor, "fd", "I");
mFileDescription = env->NewObject(cFileDescriptor,iFileDescriptor);
env->SetIntField(mFileDescription,fdID,(jint)fd);
```
This code will correctly set the fd field of the FileDescriptor object to the value of the fd variable.

**Comment by master5277** [comment]
Thanks，My problem has benn resolved.
