### ISSUE TITLE
file not found and Use of undeclared identifier 'ioctl'

### ISSUE THREAD

**Issue by master5277** [xmaihh/Android-Serialport#43]
抱歉，打扰到您了，我想请问再导入工程之后，工程可以运行，但是termios.h文件出现
'sys/cdefs.h' file not found 
'sys/ioctl.h' file not found
'sys/types.h' file not found
'stdint.h' file not found
'linux/termios.h' file not found
Unknown type name '__BEGIN_DECLS'
Use of undeclared identifier 'ioctl'
Use of undeclared identifier 'TCGETS'
Use of undeclared identifier 'ioctl'
Use of undeclared identifier 'TCXONC'
请问怎样解决？

**Comment by xmaihh** [comment]
可能是因为你没有下载和配置正确的 NDK（Native Development Kit）。

1. 访问 Android 开发者网站（[https://developer.android.com/ndk/）下载最新版本的](https://developer.android.com/ndk/%EF%BC%89%E4%B8%8B%E8%BD%BD%E6%9C%80%E6%96%B0%E7%89%88%E6%9C%AC%E7%9A%84) NDK。

2. 解压下载的 NDK 压缩包到你选择的目录中。

3. 配置环境变量：将 NDK 的路径添加到你的系统环境变量中，以便编译器可以找到所需的头文件和库。

**Comment by master5277** [comment]
好的，写写

**Comment by master5277** [comment]
谢谢
