### ISSUE TITLE
多串口同时接收和发送数据怎样做？

### ISSUE THREAD

**Issue by master5277** [xmaihh/Android-Serialport#44]
抱歉，再次打扰您了，我的情况是这样的：我已经成功实现了使用您的代码完成了单个串口的读写操作，通过读线程来接收数据，通过写线程来发送数据，并且使用SerialHelper类创建了三个实例对象分别管理三个串口的读写操作，希望能够实现三个串口的同时发送和接收数据，但是我在开启了一个串口的发送和接收之后，第二个串口就不可以实现正常的发送和接收了，请问应该按照怎样的思路才可以实现三个串口的同时接收和发送数据？

**Comment by MagicZhang1-ctrl** [comment]
谢谢
