### ISSUE TITLE
串口发送成功了，硬件已响应，但是程序不会收到结果（如果用其他串口软件开启一下串口后，用此项目就能显示到接收的结果）

### ISSUE THREAD

**Issue by GAOli-cong** [xmaihh/Android-Serialport#48]
设备关机重启之后，用此项目能发送数据，但是不会接收响应结果，需要用其他软件连接一下串口后，这个项目又能看的响应了，但是设备如果再次开关机重启，又不会收到响应。请问这样的问题大概出在哪里？

**Comment by xmaihh** [comment]
可能的原因有：
1.  串口资源占用 :在某些情况下,其他应用程序可能会占用串口资源,导致您的程序无法正常访问。请检查其他应用是否占用了串口,关闭这些应用后重试。
2. 设备初始化顺序:有时设备的启动过程中,通信协议可能需要进行某些初始化操作。您的程序可能在初始化完成之前就开始尝试通信,从而导致错误。检查设备的启动时序,调整程序中通信初始化的时机。

**Comment by GAOli-cong** [comment]
感谢大佬回复，但是奇怪的能发送成功，就是收不到响应DataReceived，如果我用一个其他的串口工具，只需要点击开启对应串口(然后将这个串口工具杀死)，此时在返回到这个项目中，发送完数据，就会显示接收的消息。
