### ISSUE TITLE
如果我要读取卡片ID应该怎么做。

### ISSUE THREAD

**Issue by luhuanxml** [xmaihh/Android-Serialport#50]
```
 serialHelper = object : SerialHelper(NFCHelper.SERIAL_PORTS, NFCHelper.BAUDRATE) {
            override fun onDataReceived(comBean: ComBean) {

                LogTool.print("nfc_read", Gson().toJson(comBean))
            }

        }
        serialHelper.open()
```
接收到的数据
{"bRec":[-3,-3,-3,-3,-3,-3],"sComPort":"/dev/ttyHSL1","sRecTime":"09:06:49"}
{"bRec":[-3,-3,-3,-3],"sComPort":"/dev/ttyHSL1","sRecTime":"09:02:54"}
{"bRec":[-3],"sComPort":"/dev/ttyHSL1","sRecTime":"09:02:50"}

如果我只是想要刷卡的时候读取卡片的ID。应该怎么做。

**Comment by xmaihh** [comment]
bRec的数据类型是byte[] ，您的字节数组必须有某种编码。如果您有负值，则编码不能是 ASCII。一旦你弄清楚了这一点，你就可以使用以下方法将一组字节转换为字符串：
```
byte[] bytes = {...}
String str = new String(bytes, StandardCharsets.UTF_8); // for UTF-8 encoding
```

**Comment by luhuanxml** [comment]
如何防止我打开的程序不生效，被其他的程序抢占。
