### ISSUE TITLE
数据读取不全应该怎么解决

### ISSUE THREAD

**Issue by luhuanxml** [xmaihh/Android-Serialport#51]
![image](https://github.com/xmaihh/Android-Serialport/assets/19920279/0f8dae67-9491-4ea0-9c62-c5209c8e46bd)

版本2.1.1

**Comment by xmaihh** [comment]
当串口数据接收分段时,需要对接收到的数据进行重组,将属于同一数据帧(或数据包)的分段数据组装起来,以恢复出完整的数据帧。

**Comment by luhuanxml** [comment]
![image](https://github.com/xmaihh/Android-Serialport/assets/19920279/f010fbdf-2ed6-4c6d-9d1c-be422d9335c5)
如何重组可以指导一下吗，第一次用。不是很懂原理。只是每次读取的时候偶尔会分段返回，一次不返回完全，要等下一次卡片贴上去的时候才返回，我的send间隔时间500ms

**Comment by xmaihh** [comment]
你的工程大致工作流程是通过Uart串口连接NFC模块，实现NFC设备间数据传输的对吗

你可以将NFC模块连接到电脑，打开串口调试助手，测试是否存在数据读取不全的问题

**Comment by luhuanxml** [comment]
的确是模拟nfc功能，设备厂商提供了命令码。您说的意思是还是我的模块有可能有问题是吧，我下载了一些其他的测试软件，在显示16进制的时候没有出现卡号分割的问题。

**Comment by xmaihh** [comment]
你需要参考这部分实现处理一下数据读取，[粘包处理](https://github.com/xmaihh/Android-Serialport/tree/master?tab=readme-ov-file#7%E7%B2%98%E5%8C%85%E5%A4%84%E7%90%86)

**Comment by MagicZhang1-ctrl** [comment]
> 的确是模拟nfc功能，设备厂商提供了命令码。您说的意思是还是我的模块有可能有问题是吧，我下载了一些其他的测试软件，在显示16进制的时候没有出现卡号分割的问题。

请问您现在解决对接收到的分段数据进行重组的问题了吗？

**Comment by luhuanxml** [comment]
我用这个库始终没有解决，最后我选择了   implementation 'com.github.F1ReKing:Android-SerialPort:1.5.1' 这个库。使用上很流畅，没有问题。
