### ISSUE TITLE
请问5.0以后如何申请权限

### ISSUE THREAD

**Issue by andyy24** [xmaihh/Android-Serialport#6]
请问5.0以后如何申请权限

**Comment by xmaihh** [comment]
使用Android-Serialport是不需要申请任何Android 权限的，不需要在manifest文件注册任何权限

**Comment by andyy24** [comment]
> 使用Android-Serialport是不需要申请任何Android 权限的，不需要在manifest文件注册任何权限

adb shell  chmod 666 /dev/ttyS1    这段可以在代码里运行吗？

**Comment by xmaihh** [comment]
@andyy24  可以，[](https://github.com/xmaihh/Android-Serialport/blob/c36af2352f3b78ef427968b3ad64d001414090a0/serialport/src/main/java/android_serialport_api/SerialPort.java#L206)

**Comment by andyy24** [comment]
> @andyy24 可以，示例代码看这里 https://github.com/xmaihh/Android-Serialport/blob/master/serialport/src/main/java/android_serialport_api/SerialPort.java#L206

非常感谢，我去试试！

**Comment by sinduanan** [comment]
> @andyy24 可以，示例代码看这里 https://github.com/xmaihh/Android-Serialport/blob/master/serialport/src/main/java/android_serialport_api/SerialPort.java#L206

这个不是在serialHelper.open()的时候内部就实现了吗  ？   咋还需要单独在申请呢
