### ISSUE TITLE
在读取串口数据的线程里，字符设备文件的.available() 总是返回0的，所以出现有时读取不到串口数据

### ISSUE THREAD

**Issue by beyondbycyx** [xmaihh/Android-Serialport#9]
https://stackoverflow.com/questions/5826198/inputstream-available-is-0-always ，这里有说明，应该改为 `read()` 才行。而且我现在出现了并发传过来的多个信号，只有一个信号读取到，其他的信号都被忽略了。不知这个问题，你解决的了吗？并发数据传过来的读取问题

**Comment by xmaihh** [comment]
我目前没有遇到出现并发传过来的多个信号,只有一个信号读取到,其他信号丢失的问题

**Comment by guodonghuang** [comment]
我也有类似问题，就是一个指令要发送多次，才能有响应数据，但是响应数据会有多个重复字段，最后还一串000000000，是不是前几次被阻塞了

**Comment by xmaihh** [comment]
请参考[iissues12](https://github.com/xmaihh/Android-Serialport/issues/12)
